### ISSUE TITLE
Allow multiple plugin names with unique suffix

### ISSUE THREAD

**Issue by jordanwilson230** [GoogleContainerTools/krew-index#43]
I've got about 5 minutes before I must leave work here, so I apologize for my scattered-brained writing!  ha. Basically, the kubectl plugin docs subtly hint at using a naming strategy starting with a common base and ending with a unique suffix.  So for example, I have the following plugins which I'm trying to port over:
```
kubectl-prompt
kubectl-prompt-add
kubectl-prompt-list
kubectl-prompt-remove
kubectl-prompt-warning
```

I believe kubectl's intention was to promote smaller, distinct/isolated code for a given plugin.  I'm just guessing here :)  In any case, I was hoping the metadata.name field might accept multiple plugin names (assuming they are extensions/suffixes of the base plugin), like so:

```
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name:
    - prompt
    - prompt-list
    - prompt-add
    - prompt-remove
    - prompt-warning
```

Is it possible to get this to show up in the search/index as just 'prompt', while still creating a soft-link for these supporting plugin files?

Of course, I could combine all of these into a single plugin file, specifically for Krew and to get this imported.  I'm curious what your thoughts are @ahmetb as well as others. 

PS: I've renamed the kubectl-ssh plugin (from github.com/jordanwilson230/kubectl-plugins) to kubectl-user-exec and finished the plugin manifest. I noticed the PR currently open and see now the type of issues it could cause, haha.  Will submit a PR for that shortly.

**Comment by ahmetb** [comment]
If there things are indeed separate plugins doing separate things, they should be packaged and installed separately. If they are just subcommands, you should have a single entrypoint.

If you have a single executable named `kubectl-prompt`, any subcommands specified will be passed to that executable as command line arguments (argv).

Similarly, if they are subcommands implemented as separate executables, you should still have a "single entrypoint executable" which executes the specified subcommand.

Here's a simple test: Do you want to see all these subcommands listed as plugins in "kubectl plugins list"? (I think not.)

For now this is _wontfix_. If we see a common pattern of people "developing plugins with multiple subcommands also registered as plugins", we might consider solving this, but I doubt that won't happen.

**Comment by ahmetb** [comment]
(Also please consider opening issues that aren't related to the plugin index repo to the main repo https://github.com/GoogleContainerTools/krew.)

**Comment by jordanwilson230** [comment]
Sure thing @ahmetb. Just to clarify, this is a concept that I understand well, but needed to clarificy whether krew accomodates this. As it states:

> This design choice ensures that plugin sub-commands can be implemented across multiple 
> files, if needed, and that these sub-commands can be nested under a “parent” plugin command:
[The design proposed](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/#invocation-of-the-longest-executable-filename)

I understand now that krew does not accommodate for this, so thanks for the answer.

Noted on using the krew repo for non maintainer issues moving forward.

**Comment by ahmetb** [comment]
Makes sense, I'm open to a proposal on Krew repo, if you can put it in writing other developers who agree can participate as well.

**Comment by ahmetb** [comment]
cc: @juanvallejo 

I would not worry about the landrush for now, although we're enforcing it for really common nouns/verbs.

I think we'll be solving this by decentralizing the plugin index going forward. For example, if we allow you to install plugins with repo names like `krew install jordanwilson230/kubectl-prompt`, this would be a problem only for the users trying to install multiple plugins with the same name (rare case).
