### ISSUE TITLE
Error when running sniff plugin

### ISSUE THREAD

**Issue by jordanwilson230** [GoogleContainerTools/krew-index#48]
After installing via krew and running it via ```kubectl sniff kafka-0``` I get the following output:

```
Error: No Auth Provider found for name "gcp"
```
Tried numerous options, flags, etc., but everything returns the same error.
Note: Installing to Mac, darwin.  tcpdump is installed. wireshark installed.

**Comment by jordanwilson230** [comment]
Maintainer is aware of the issue and cut a new release for a fix.  Issue is being tracked in the reference link above.

**Comment by jordanwilson230** [comment]
Also, sorry for opening the issue here instead of the main Krew repo. I've just been on this page so long the past few days, ha.

**Comment by ahmetb** [comment]
Haha no problem. I will close it here.
