### ISSUE TITLE
Add homepage for plugin manifests

### ISSUE THREAD

**Issue by superbrothers** [GoogleContainerTools/krew-index#92]
This is an umbrella issue that adds homepage for plugin manifests. 

- [x] access-matrix
- [x] bulk-action
- [x] ca-cert
- [x] change-ns
- [x] cssh
- [x] debug-shell
- [x] exec-all
- [x] exec-as
- [x] get-all
- [x] gke-credentials
- [x] krew
- [x] kubesec-scan
- [x] match-name
- [x] mtail
- [x] node-admin
- [x] open-svc
- [x] pod-logs
- [x] pod-shell
- [x] prompt
- [x] rbac-lookup
- [x] rbac-view
- [x] resource-capacity
- [x] restart
- [x] rm-standalone-pods
- [x] sniff
- [x] ssh-jump
- [x] sudo
- [x] view-secret
- [x] view-serviceaccount-kubeconfig
- [x] view-utilization
- [x] warp

 /ref https://github.com/GoogleContainerTools/krew/pull/158

**Comment by jordanwilson230** [comment]
@superbrothers i have```exec-as``` posted [here](https://github.com/jordanwilson230/kubectl-plugins#kubectl-ssh) as ```kubectl ssh```. If you'd like, I'll try to add a README specific for the Krew plugins (prompt and exec-as). tomorrow.

**Comment by jordanwilson230** [comment]
@superbrothers @ahmetb Here is an updated homepage link for [exec-as](https://github.com/jordanwilson230/kubectl-plugins/tree/krew#kubectl-exec-as) and [prompt](https://github.com/jordanwilson230/kubectl-plugins/tree/krew#kubectl-prompt).

Let me know if you see anything missing.

**Comment by superbrothers** [comment]
@jordanwilson230 Could you update your plugin manifests to add/update homepage?

**Comment by jordanwilson230** [comment]
Sure thing, @superbrothers.  I'll send a PR over to you in just a bit.

**Comment by ahmetb** [comment]
I think this is done now?

**Comment by jordanwilson230** [comment]
@ahmetb yeah, https://github.com/GoogleContainerTools/krew-index/pull/113

**Comment by ahmetb** [comment]
Thanks all!
